# Copyright 2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8


inherit cargo desktop git-r3 xdg

DESCRIPTION="Gentoo installer: btrfs layout, per-hardware kernel, Limine; GTK4 and TUI"
HOMEPAGE="https://github.com/tarilka0gg/gentoo-installer"
EGIT_REPO_URI="https://github.com/tarilka0gg/gentoo-installer.git"

LICENSE="GPL-2+"
# Dependent crate licenses (generated by packaging/gentoo/gen-ebuild-data.py)
LICENSE+=" Apache-2.0 Apache-2.0-with-LLVM-exceptions BSD Boost-1.0 CDLA-Permissive-2.0 ISC LGPL-2.1+ MIT Unicode-3.0 Unlicense ZLIB openssl"
SLOT="0"

IUSE="+gui"

# What the installer shells out to on the live system
RDEPEND="
	dev-vcs/git
	sys-apps/pciutils
	sys-block/parted
	sys-boot/limine
	sys-fs/btrfs-progs
	sys-fs/dosfstools
	sys-kernel/dracut
	gui? (
		>=gui-libs/gtk-4.0:4
		>=gui-libs/libadwaita-1.4:1
	)
"
DEPEND="
	gui? (
		>=gui-libs/gtk-4.0:4
		>=gui-libs/libadwaita-1.4:1
	)
"
BDEPEND="virtual/pkgconfig"

QA_FLAGS_IGNORED="usr/bin/installer-cli usr/bin/installer-gui"

pkg_setup() {
	rust_pkg_setup
}

src_unpack() {
	git-r3_src_unpack
	cargo_live_src_unpack
}

src_compile() {
	cargo_src_compile -p installer-cli $(usev gui '-p installer-gui')
}

src_test() {
	cargo_src_test --workspace --
}

src_install() {
	cargo_src_install --path installer-cli
	if use gui; then
		cargo_src_install --path installer-gui
		domenu packaging/io.github.tarilka0gg.GentooInstaller.desktop
	fi
	domenu packaging/io.github.tarilka0gg.GentooInstaller.Text.desktop
	insinto /usr/share/metainfo
	doins packaging/io.github.tarilka0gg.GentooInstaller.metainfo.xml
	insinto /usr/share/icons/hicolor/scalable/apps
	doins packaging/icons/gentoo-installer.svg
	einstalldocs
}

pkg_postinst() {
	xdg_pkg_postinst
	ewarn "gentoo-installer ERASES DISKS. Run it from a live system, as root."
}

pkg_postrm() {
	xdg_pkg_postrm
}
