//! Generates `/etc/fstab` for the freshly-partitioned target, by UUID (not device path,
//! which can shift between boots on multi-disk systems).

use crate::partition::{Layout, Partitions, RootFs};
use crate::process::run;
use std::path::Path;

pub async fn generate(target: &Path, layout: &Layout, parts: &Partitions) -> crate::Result<()> {
    let esp_uuid = blkid_uuid(&parts.esp).await?;
    let swap_uuid = blkid_uuid(&parts.swap).await?;
    let root_uuid = blkid_uuid(&parts.root).await?;

    let mut fstab = String::from("# Generated by gentoo-installer\n\n");
    fstab.push_str(&format!(
        "UUID={esp_uuid}  /boot  vfat  defaults,noatime  0 2\n"
    ));
    fstab.push_str(&format!("UUID={swap_uuid}  none  swap  sw  0 0\n"));

    match layout.root_fs {
        RootFs::Btrfs => {
            fstab.push_str(&format!(
                "UUID={root_uuid}  /  btrfs  subvol=@,compress=zstd:1,noatime  0 1\n"
            ));
            for (subvol, mountpoint) in [("@home", "/home"), ("@var", "/var"), ("@log", "/var/log")] {
                fstab.push_str(&format!(
                    "UUID={root_uuid}  {mountpoint}  btrfs  subvol={subvol},compress=zstd:1,noatime  0 2\n"
                ));
            }
        }
        RootFs::Ext4 => {
            fstab.push_str(&format!("UUID={root_uuid}  /  ext4  defaults,noatime  0 1\n"));
        }
    }

    tokio::fs::write(target.join("etc/fstab"), fstab).await?;
    Ok(())
}

async fn blkid_uuid(device: &str) -> crate::Result<String> {
    let out = run("blkid", &["-s", "UUID", "-o", "value", device]).await?;
    let uuid = out.trim();
    if uuid.is_empty() {
        return Err(crate::Error::Other(anyhow::anyhow!(
            "blkid returned no UUID for {device}"
        )));
    }
    Ok(uuid.to_string())
}
